#install bzr
- name: install bzr for redhat
  yum: name='bzr,libmysqlclient-devel' state=present disable_gpg_check=yes
  when: ansible_os_family == 'RedHat'

- name: install bzr for ubuntu
  apt: name='bzr,libmysqlclient-dev' state=present
  when: ansible_distribution == 'Ubuntu'

- name: install bzr for CentOS
  yum: name='bzr,libmysqlclient-devel' state=present disable_gpg_check=yes
  when: ansible_distribution == 'CentOS'

- name: install bzr for Debian
  apt: name='bzr,libmysqlclient-dev' state=present
  when: ansible_distribution == 'Debian'

- name: install libmysqlclient-devel for SLES
  zypper: name=libmysqlclient-devel state=present
  when: ansible_distribution == 'SLES'

- name: copy bzr for SLES
  copy: src=bzr-2.5.1-14.el7.aarch64.rpm dest=/tmp/bzr-2.5.1-14.el7.aarch64.rpm mode=0777
  when: ansible_distribution == 'SLES'

- name: install bzr for SLES
  shell: cd /tmp && rpm -ivh bzr-2.5.1-14.el7.aarch64.rpm
  when: ansible_distribution == 'SLES'
  ignore_errors: yes

- name: copy sysbench.tar.gz
  copy: src=sysbench.tar.gz dest=/tmp/sysbench.tar.gz mode=0777

- name: tar sysbench.tar.gz
  shell: cd /tmp && tar -xvf sysbench.tar.gz && rm sysbench.tar.gz
