
- hosts: Device
  vars_files:
  - ~/caliper_output/configuration/config/hosts
  tasks:
    - name: remove latest data
      file:
        path: ~/{{root_dir}}/{{app_dir}}/{{app_name_dir}}/{{app_test_tool_dir}}/
        state: absent


    - name: run iperf on client with 1 thread
      command: pushd /tmp/nginx/nginx_scripts && ./nginx_conf.sh && ~/irq_0_7.sh && ./run_nginx_dstat.sh 1 $target_ip_1_10g $target_port_1 24 8
      register: logdata

    - lineinfile: create=yes  dest=~/{{root_dir}}/{{app_dir}}/{{app_name_dir}}/{{app_test_tool_dir}}/iper_output.txt line="{{ logdata.stdout }}" state=present

    - name: mkdir result
      file: dest=~/result state=directory

    - name: fetch result
      fetch:
        src: ~/{{root_dir}}/{{app_dir}}/{{app_name_dir}}/{{app_test_tool_dir}}/iper_output.txt
        dest: ~/{{root_dir}}/{{app_dir}}/{{app_name_dir}}/{{app_test_tool_dir}}/result/iper_output.txt
        flat: yes
