
- hosts: Device
  vars_files:
  - group_vars/nginx
  tasks:
    - name: remove latest data
      file:
        path: /tmp/nginx_output.txt
        state: absent

    - name: run nginx on client
      shell: cd /tmp/tinymembench && ./tinymembench
      register: logdata
      ignore_errors: yes

    - lineinfile: create=yes  dest=/tmp/nginx_output.log line="{{ logdata.stdout }}" state=present


    - name: fetch result
      fetch:
        src: /tmp/nginx_output.txt
        dest: /tmp/nginx_output.txt
        flat: yes
