
- hosts: Device
  vars_files:
  - group_vars/nginx
  tasks:
    - name: remove latest data
      file:
        path: /tmp/nginx_output.txt
        state: absent

    - name: run nginx on client
      command: ./run_weighttp_script.sh {{target_user_name}} {{target_ip_1_10g}} {{target_port_1}} 24 8 25000000 index0.html
      register: logdata

    - lineinfile: create=yes  dest=/tmp/nginx_output.txt line="{{ logdata.stdout }}" state=present


    - name: fetch result
      fetch:
        src: /tmp/nginx_output.txt
        dest: /tmp/nginx_output.txt
        flat: yes
