- name: copy file
  copy: src=dhrystone.tar.gz dest=/tmp/dhrystone.tar.gz owner=root group=root mode=0755

- name: tar file
  shell: cd /tmp && tar xvf dhrystone.tar.gz && rm -rf dhrystone.tar.gz

- name: run install
  shell: "cd /tmp/dhrystone && chmod 777 install.sh && ./install.sh"