- name: mkdir scripts
  shell: "mkdir -p /tmp/compile"

- name: download kernel-dev.tar.gz
  shell: cd /tmp/compile && wget -c www.estuarydev.org/caliper/kernel-dev.tar.gz

- name: copy file
  copy: src=compile_test.sh dest=/tmp/compile/compile_test.sh mode=0777