---
# tasks file for get_hw_info

- name: install jq for redhat
  yum: name=jq state=present disable_gpg_check=yes
  when: ansible_os_family == 'RedHat'

- name: install jq for ubuntu
  apt: name=jq state=present
  when: ansible_distribution == 'Ubuntu'

- name: install ethtool for redhat
  yum: name=ethtool state=present disable_gpg_check=yes
  when: ansible_os_family == 'RedHat'

- name: install ethtool for ubuntu
  apt: name=ethtool state=present
  when: ansible_distribution == 'Ubuntu'

- name: install lshw for redhat
  yum: name=lshw state=present disable_gpg_check=yes
  when: ansible_os_family == 'RedHat'

- name: install lshw for ubuntu
  apt: name=lshw state=present
  when: ansible_distribution == 'Ubuntu'

- name: install lsblk for redhat
  yum: name=lsblk state=present disable_gpg_check=yes
  when: ansible_os_family == 'RedHat'

- name: install lsblk for ubuntu
  apt: name=lsblk state=present
  when: ansible_distribution == 'Ubuntu'
  ignore_errors: yes

- name: install dmidecode for redhat
  yum: name=dmidecode state=present disable_gpg_check=yes
  when: ansible_os_family == 'RedHat'

- name: install dmidecode for ubuntu
  apt: name=dmidecode state=present
  when: ansible_distribution == 'Ubuntu'

- name: copy config_info_run.sh file
  copy: src=config_info_run.sh dest=/tmp/config_info_run.sh mode=0755
- name: copy hw-functions file
  copy: src=hw-functions dest=/tmp/hw-functions mode=0755
- name: remove latest data
  file:
    path: /tmp/config_output.json
    state: absent

- name: run config_info_run.sh
  shell: pip install ansible && cd /tmp && ./config_info_run.sh
  register: logdata
  ignore_errors: yes
  become: true
  become_method: sudo
  become_user: root

- name: fetch result
  fetch:
    src: /tmp/config_output.json
    dest: /tmp/config_output.json
    flat: yes
